baseurl = "http://www.hcbravo.org/"
languageCode = "en-us"
title = "CMSC320 Introduction to Data Science"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Héctor Corrada Bravo"
	description = "Data Science course at the University of Maryland Department of Computer Science"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/hcorrada/IntroDataSci.git"

	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "deep-orange"
    	accent  = "blue"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = "hcorrada"
	github  = "hcorrada"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 0

[[menu.main]]
	name   = "Logistics"
	url    = "logistics.html"
	weight = 10

[[menu.main]]
	name   = "Lecture Notes"
	url    = "lecture-notes/"
	weight = 20

[[menu.main]]
	name   = "Resources"
	url    = "resources.html"
	weight = 30

[[menu.main]]
	name   = "Projects"
	url    = "projects/"
	weight = 40


[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
